### ISSUE TITLE
(周记模板) QG训练营网络组第一周周记：2016年4月17日(800字以上)

### ISSUE THREAD

**Issue by wentianxin** [QGStudio/Web-Camp#2]
## 生活随记

>  Note : 记录这一周的主要精力（请不要流水账, 看完之可自行删除）

正文
## 学习情况

> 记录这一周的学习情况和学习内容（看完之可自行删除）

正文 
## 一周总结

> 这一周的总结，对这一周的学习规划的完成情况 （看完之可自行删除）

正文 
## 存在问题

> 目前存在问题 （看完之后可自行删除）

正文
## 下周规划

> 下一周的学习规划，如何解决问题 （看完之后可自行删除）

正文

---

**周记**

> 1. 请使用markdown编写自己的周记
> 2. 周记标题用`一级标题 # 标明`、
> 3. 周记共分为 `生活随记` `学习情况` `一周总结` `存在问题` `下周规划`五部分 （请用`二级标题 # 标注`）

**Comment by cposture** [comment]
周记的文件名有作什么要求吗？

**Comment by wentianxin** [comment]
@cposture 嗯嗯。 QG训练营网络组第一周周记：2016年4月17日。这是每篇周记的文件名
